"""Builds the harness logo PNGs (16 and 32 px, 8-bit RGBA, non-interlaced) and the embedded copy
in src/logos.generated.ts.

Usage: python scripts/gen-logos.py <dir with source icons>

The source icons are the official marks each project publishes (the same files the NeuroSquad
desktop app shows). Adding a harness: drop `<id>.png` (square, >= 32 px) into the source dir, add
the id to SOURCES below and an entry to HARNESS_LOGOS in src/logos.ts, re-run (only with the
owner's permission to show the mark).
Requires Pillow. The `command` icon is drawn here, it is our own neutral mark.
"""
import base64, io, os, sys
from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
# Claude Code is deliberately absent: at Anthropic's request no Claude Code logo is shipped; it
# gets the neutral "CC" glyph badge from HARNESS_LOGOS in every mode.
SOURCES = {
    'codex': 'codex-cli-icon.png',
    'opencode': 'opencode-icon.png',
}
SIZES = (16, 32)


def command_icon(size=256):
    im = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    r = size // 5
    d.rounded_rectangle([0, 0, size - 1, size - 1], radius=r, fill=(52, 52, 58, 255))
    w = size // 12
    ink = (232, 232, 236, 255)
    # prompt chevron
    d.line([(size * 0.22, size * 0.30), (size * 0.44, size * 0.50), (size * 0.22, size * 0.70)], fill=ink, width=w, joint='curve')
    # cursor underscore
    d.line([(size * 0.52, size * 0.70), (size * 0.78, size * 0.70)], fill=ink, width=w)
    return im


def png_bytes(im):
    buf = io.BytesIO()
    im.save(buf, format='PNG', optimize=True)  # Pillow never interlaces unless asked
    return buf.getvalue()


def main():
    src_dir = sys.argv[1]
    out = {}
    images = {k: Image.open(os.path.join(src_dir, v)).convert('RGBA') for k, v in SOURCES.items()}
    images['command'] = command_icon()
    for key, im in images.items():
        out[key] = {}
        for s in SIZES:
            small = im.resize((s, s), Image.LANCZOS)
            data = png_bytes(small)
            with open(os.path.join(PKG, 'assets', 'logos', f'{key}-{s}.png'), 'wb') as f:
                f.write(data)
            out[key][s] = base64.b64encode(data).decode('ascii')
    lines = [
        '// Generated by scripts/gen-logos.py - do not edit by hand.',
        '// Base64 PNGs (8-bit RGBA, non-interlaced) of each harness logo at 16 and 32 px.',
        '// The logos identify the CLI only and are the property of their owners (see README).',
        '',
        'export const LOGO_PNG_BASE64: Readonly<Record<string, Readonly<Record<16 | 32, string>>>> = {',
    ]
    for key, sizes in out.items():
        lines.append(f"  '{key}': {{")
        for s, b in sizes.items():
            lines.append(f"    {s}: '{b}',")
        lines.append('  },')
    lines.append('}')
    with open(os.path.join(PKG, 'src', 'logos.generated.ts'), 'w', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
