// The plugin for OpenCode 2 (npm `@opencode/cli`). OpenCode 2 has a new plugin
// API — a module whose default export is `{ id, setup(ctx) }`, hooks
// registered through `ctx.<domain>.hook(name, cb)`, events from
// `ctx.event.subscribe()` as `{ type, data }` — so the 1.x plugin does not load
// there. This one reports the same facts in the same words to the same
// endpoint (`…/hook/<token>/<agentId>/OpenCode`, ./hooks.ts):
//
//   - `working` / `finished` — a root session's `session.execution.started` /
//                              `succeeded` | `failed` | `interrupted`
//   - `needs-input`          — `permission.asked` and a question tool's
//                              `form.created`; reported at once (2.x's own
//                              approval runs in `permission.evaluate`, before
//                              any prompt is shown)
//   - `answered`             — `permission.replied`, `form.replied`/`cancelled`
//   - `retry`                — `session.retry.scheduled`
//   - `subagent-start/stop`  — a child session's executions
//
// Also:
//   - dangerous mode is live: `permission.evaluate` turns an "ask" into
//     "allow" while the agent's dangerous mode is on (the host is asked per
//     request); a deny rule never reaches it;
//   - the launched model wins on resume: `session.switchModel` at start;
//   - OpenRouter attribution: the `session` `model.request` hook sets the
//     attribution headers on every request to OpenRouter.
//
// Plain ESM in a folder of its own: 2.x loads a local plugin only from a
// directory whose `server` entry is imported. Nothing secret in the files: the
// hook base URL (token in the path) arrives in the process environment.
import {
  OPENCODE_ATTRIBUTION_ENV,
  OPENCODE_HOOK_ENV,
  OPENCODE_LIVE_DANGER_ENV,
  OPENCODE_MODEL_ENV
} from './plugin.js'

/** Folder inside the OpenCode layer dir that holds the 2.x plugin. */
export const OPENCODE_V2_PLUGIN_DIR = 'neurosquad-plugin-v2'

/** The agent's own session id (2.x takes the caller's — `--session <id>` creates it). */
export const OPENCODE_SESSION_ENV = 'NEUROSQUAD_OPENCODE_SESSION'

/** Hook-endpoint event of the live dangerous-mode question. */
export const OPENCODE_PERMISSION_HOOK_EVENT = 'OpenCodePermission'

/** The plugin folder's package.json: an ES module with a `server` entry. */
export const OPENCODE_V2_PLUGIN_PACKAGE = `${JSON.stringify(
  {
    name: 'neurosquad-opencode-bridge',
    private: true,
    type: 'module',
    main: './server.js',
    exports: { '.': './server.js', './server': './server.js' }
  },
  null,
  2
)}\n`

export function buildOpenCodeV2PluginSource(): string {
  return `// Generated by NeuroSquad — reports this OpenCode agent's turns to its host.
// Rewritten when it changes; edits here are lost.
const env = (name) => process.env[name] || ''
const clip = (text, max) => (text.length > max ? text.slice(0, max - 1) + '…' : text)

export default {
  id: 'neurosquad',
  setup: async (ctx) => {
    const base = env('${OPENCODE_HOOK_ENV}')
    const quiet = async (work) => {
      try {
        return await work()
      } catch {
        return undefined
      }
    }
    const ask = async (path, body, ms) => {
      const res = await fetch(base + '/' + path, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
        signal: AbortSignal.timeout(ms)
      })
      return res.json()
    }
    const post = (body) => {
      if (!base) return
      try {
        fetch(base + '/OpenCode', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(body),
          signal: AbortSignal.timeout(2000)
        }).catch(() => {})
      } catch {}
    }

    // Sets the attribution headers for OpenRouter requests.
    let attribution = null
    try {
      const parsed = JSON.parse(env('${OPENCODE_ATTRIBUTION_ENV}') || 'null')
      if (parsed && typeof parsed === 'object') attribution = parsed
    } catch {}
    if (attribution) {
      await quiet(() =>
        ctx.session.hook('model.request', (event) => {
          try {
            if (event && event.model && event.model.providerID === 'openrouter' && event.headers) {
              Object.assign(event.headers, attribution)
            }
          } catch {}
        })
      )
    }
    if (!base) return

    const child = new Map()
    const childAgent = new Map()
    const childBusy = new Set()
    const busy = new Set()
    const pending = new Map()
    const infoOf = (res) => (res && res.data && typeof res.data === 'object' ? res.data : res)
    const isChild = async (id) => {
      if (!id) return false
      if (child.has(id)) return child.get(id)
      const info = infoOf(await quiet(() => ctx.session.get({ sessionID: id })))
      if (!info || typeof info !== 'object') return false
      const value = Boolean(info.parentID)
      child.set(id, value)
      if (value && typeof info.agent === 'string') childAgent.set(id, info.agent)
      return value
    }
    const subPrefix = async (id) => {
      if (!(await isChild(id))) return ''
      const name = childAgent.get(id)
      return name ? 'Subagent ' + name + ': ' : 'Subagent: '
    }
    const childStopped = (id) => {
      if (!id || !childBusy.has(id)) return
      childBusy.delete(id)
      post({ event: 'subagent-stop', sessionID: id })
    }
    const describePermission = (p) => {
      const what = String(p.action || 'a tool')
      const meta = p.metadata || {}
      const resources = Array.isArray(p.resources) ? p.resources.filter((r) => r && r !== '*') : []
      const target =
        typeof meta.command === 'string' ? meta.command
        : typeof meta.filepath === 'string' ? meta.filepath
        : typeof meta.url === 'string' ? meta.url
        : resources.join(' ; ')
      return 'OpenCode needs your permission: ' + what + (target ? ' — ' + target : '')
    }
    const describeForm = (form) => {
      const fields = Array.isArray(form.fields) ? form.fields : []
      const first = fields[0] || {}
      const kind = form.metadata && form.metadata.kind
      return kind === 'question'
        ? 'OpenCode is asking: ' + String(first.description || first.title || 'a question')
        : 'OpenCode needs your input: ' + String(form.title || first.title || 'a form')
    }
    const waiting = async (id, sessionID, detail) => {
      if (!id || pending.has(id)) return
      pending.set(id, sessionID)
      post({ event: 'needs-input', sessionID, detail: clip((await subPrefix(sessionID)) + detail, 300) })
    }
    const answered = (id, sessionID) => {
      if (!id || !pending.has(id)) return
      const known = pending.get(id)
      pending.delete(id)
      post({ event: 'answered', sessionID: sessionID || known })
    }

    if (env('${OPENCODE_LIVE_DANGER_ENV}') === '1') {
      await quiet(() =>
        ctx.permission.hook('evaluate', async (event) => {
          try {
            if (!event || event.effect !== 'ask') return
            const answer = await ask(
              '${OPENCODE_PERMISSION_HOOK_EVENT}',
              { permission: event.action, patterns: event.resources },
              2000
            )
            if (answer && answer.allow === true) event.effect = 'allow'
          } catch {}
        })
      )
    }

    const pinnedRaw = env('${OPENCODE_MODEL_ENV}')
    const own = env('${OPENCODE_SESSION_ENV}')
    const at = pinnedRaw.indexOf('/')
    if (own && at > 0) {
      const model = { providerID: pinnedRaw.slice(0, at), id: pinnedRaw.slice(at + 1) }
      void (async () => {
        const info = infoOf(await quiet(() => ctx.session.get({ sessionID: own })))
        const current = info && info.model
        if (!current || (current.providerID === model.providerID && current.id === model.id)) return
        await quiet(() => ctx.session.switchModel({ sessionID: own, model }))
      })()
    }

    const turn = async (id, status) => {
      if (!id) return
      if (await isChild(id)) {
        if (status === 'busy' && !childBusy.has(id)) {
          childBusy.add(id)
          post({ event: 'subagent-start', sessionID: id, agent: childAgent.get(id) || '' })
        } else if (status === 'idle') childStopped(id)
        return
      }
      if (status === 'busy' && !busy.has(id)) {
        busy.add(id)
        post({ event: 'working', sessionID: id })
      } else if (status === 'idle' && busy.has(id)) {
        busy.delete(id)
        post({ event: 'finished', sessionID: id })
      }
    }
    const handle = async (event) => {
      const type = event && event.type
      const p = (event && event.data) || {}
      switch (type) {
        case 'session.execution.started':
          await turn(p.sessionID, 'busy')
          return
        case 'session.execution.succeeded':
        case 'session.execution.failed':
          await turn(p.sessionID, 'idle')
          return
        case 'session.execution.interrupted':
          // Superseded: a new execution of the same turn follows at once.
          if (p.reason !== 'superseded') await turn(p.sessionID, 'idle')
          return
        case 'session.retry.scheduled': {
          if (!p.sessionID || (await isChild(p.sessionID))) return
          const error = p.error || {}
          post({
            event: 'retry',
            sessionID: p.sessionID,
            message: String(error.message || ''),
            next: typeof p.at === 'number' ? p.at : undefined,
            reason: typeof error.type === 'string' ? error.type : undefined
          })
          return
        }
        case 'session.created':
          if (p.sessionID) {
            child.set(p.sessionID, Boolean(p.parentID))
            if (p.parentID && typeof p.agent === 'string') childAgent.set(p.sessionID, p.agent)
          }
          return
        case 'session.deleted':
          childStopped(p.sessionID)
          return
        case 'session.status': {
          const id = p.sessionID
          if (!id) return
          const status = (p.status && p.status.type) || ''
          if (status === 'busy' || status === 'idle') await turn(id, status)
          return
        }
        case 'permission.asked':
          await waiting(p.id, p.sessionID, describePermission(p))
          return
        case 'permission.replied':
          answered(p.requestID || p.id, p.sessionID)
          return
        case 'form.created': {
          const form = p.form || {}
          await waiting(form.id, form.sessionID, describeForm(form))
          return
        }
        case 'form.replied':
        case 'form.cancelled':
          answered(p.id, p.sessionID)
          return
      }
    }
    const stop = new AbortController()
    void (async () => {
      try {
        for await (const event of ctx.event.subscribe({ signal: stop.signal })) {
          try {
            await handle(event)
          } catch {}
        }
      } catch {}
    })()
    return () => stop.abort()
  }
}
`
}
