// The OpenCode 1.x plugin that reports an agent's lifecycle to the host
// (docs/harnesses.md, "OpenCode"). OpenCode has no shell-command hooks; it has
// a plugin system — a JS module the harness imports into its own process and
// hands every bus event. So the facts Claude Code states through hooks come
// from here:
//
//   - `working`     — the main session went `busy` (a turn started)
//   - `finished`    — it went back to `idle`
//   - `needs-input` — a permission prompt or a question is waiting on the
//                     user; `detail` is what it wants ("bash — rm -rf dist")
//   - `answered`    — that prompt was answered (the turn moves again)
//   - `retry`       — OpenCode is retrying a failed request (rate limit…)
//   - `subagent-start` / `subagent-stop` — a `task` child session ran
//
// and, on every one of them, the session id: OpenCode picks its own ids
// (`ses_…`), so the host learns it here and resumes it with `--session <id>`.
//
// A permission ask is reported after a short delay and dropped if it was
// answered meanwhile: with `--auto` the TUI approves every ask within
// milliseconds, and a "needs you" for something nobody has to answer is noise.
//
// It also sets the OpenRouter attribution headers on requests to OpenRouter
// (`chat.headers`), and pins the launched model on a resumed session.
// Everything it needs arrives in the environment of its process; the file is
// the same for every agent and holds nothing secret. It never throws into
// OpenCode: every request is fire-and-forget with a timeout.
import { OPENCODE_FLAVOR, type OpenCodeFlavor } from './flavor.js'

/** File name inside the OpenCode layer dir. */
export const OPENCODE_PLUGIN_FILE = 'neurosquad-plugin.js'

/** Environment variable carrying the agent's hook base URL (token in the path). */
export const OPENCODE_HOOK_ENV = 'NEUROSQUAD_HOOK_URL'

/**
 * `provider/model` the agent was launched with (`--model`): OpenCode's TUI,
 * opening a resumed session, takes the model of that session's last message
 * over `--model`; the plugin puts the launched model on messages that still
 * carry the session's previous one.
 */
export const OPENCODE_MODEL_ENV = 'NEUROSQUAD_PINNED_MODEL'

/** How long an ask waits before it counts as "waiting on the user". */
export const OPENCODE_ASK_DELAY_MS = 700

/** JSON of headers to put on every request to OpenRouter (the attribution headers). */
export const OPENCODE_ATTRIBUTION_ENV = 'NEUROSQUAD_OPENROUTER_HEADERS'

/** Set ('1') where the plugin asks the host about each permission (OpenCode 2, ./pluginV2.ts). */
export const OPENCODE_LIVE_DANGER_ENV = 'NEUROSQUAD_LIVE_DANGER'

export function buildOpenCodePluginSource(flavor: OpenCodeFlavor = OPENCODE_FLAVOR): string {
  return `// Generated by NeuroSquad — reports this ${flavor.label} agent's turns to its host.
// Rewritten on every launch; edits here are lost.
export const NeuroSquadBridge = async ({ client }) => {
  let attribution = null
  try {
    const parsed = JSON.parse(process.env.${OPENCODE_ATTRIBUTION_ENV} || 'null')
    if (parsed && typeof parsed === 'object') attribution = parsed
  } catch {}
  // Sets the attribution headers for OpenRouter requests.
  const withHeaders = attribution
    ? {
        'chat.headers': async (input, output) => {
          try {
            if (input && input.model && input.model.providerID === 'openrouter') {
              Object.assign(output.headers, attribution)
            }
          } catch {}
        }
      }
    : {}
  const base = process.env.${OPENCODE_HOOK_ENV}
  if (!base) return withHeaders
  const post = (body) => {
    try {
      fetch(base + '/${flavor.hookEvent}', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
        signal: AbortSignal.timeout(2000)
      }).catch(() => {})
    } catch {}
  }
  const pinnedRaw = process.env.${OPENCODE_MODEL_ENV} || ''
  const pinAt = pinnedRaw.indexOf('/')
  const pinned =
    pinAt > 0 ? { providerID: pinnedRaw.slice(0, pinAt), modelID: pinnedRaw.slice(pinAt + 1) } : null
  let pinState = null
  const pin = async (input, output) => {
    try {
      if (!pinned || pinState === 'own') return
      const message = output && output.message
      const sessionID = input && input.sessionID
      if (!message || !message.model || !sessionID || (await isChild(sessionID))) return
      const m = message.model
      if (m.providerID === pinned.providerID && m.modelID === pinned.modelID) {
        if (pinState === null) pinState = 'own'
        return
      }
      if (pinState === null) pinState = { providerID: m.providerID, modelID: m.modelID }
      if (pinState.providerID !== m.providerID || pinState.modelID !== m.modelID) return
      message.model = { ...m, providerID: pinned.providerID, modelID: pinned.modelID }
    } catch {}
  }
  const child = new Map()
  const busy = new Set()
  const childBusy = new Set()
  const childAgent = new Map()
  const subPrefix = async (sessionID) => {
    if (!sessionID || !(await isChild(sessionID))) return ''
    const name = childAgent.get(sessionID)
    return name ? 'Subagent ' + name + ': ' : 'Subagent: '
  }
  const childStopped = (id) => {
    if (!id || !childBusy.has(id)) return
    childBusy.delete(id)
    post({ event: 'subagent-stop', sessionID: id })
  }
  const asks = new Map()
  const isChild = async (id) => {
    if (child.has(id)) return child.get(id)
    try {
      const res = await client.session.get({ path: { id } })
      const value = Boolean(res && res.data && res.data.parentID)
      child.set(id, value)
      return value
    } catch {
      return false
    }
  }
  const clip = (text, max) => (text.length > max ? text.slice(0, max - 1) + '…' : text)
  const describePermission = (p) => {
    const what = String(p.permission || p.type || 'a tool')
    const meta = p.metadata || {}
    const target =
      typeof meta.command === 'string' ? meta.command
      : typeof meta.filepath === 'string' ? meta.filepath
      : typeof meta.url === 'string' ? meta.url
      : Array.isArray(p.patterns) && p.patterns.length && p.patterns[0] !== '*' ? p.patterns.join(' ')
      : ''
    return clip('${flavor.label} needs your permission: ' + what + (target ? ' — ' + target : ''), 300)
  }
  const describeQuestion = (p) => {
    const first = Array.isArray(p.questions) && p.questions[0]
    const text = first ? String(first.question || first.header || '') : ''
    return clip('${flavor.label} is asking: ' + (text || 'a question'), 300)
  }
  const ask = (id, sessionID, detail) => {
    if (!id || asks.has(id)) return
    asks.set(id, setTimeout(() => {
      asks.delete(id)
      post({ event: 'needs-input', sessionID, detail })
    }, ${OPENCODE_ASK_DELAY_MS}))
  }
  const answered = (id, sessionID) => {
    const timer = id && asks.get(id)
    if (timer) {
      clearTimeout(timer)
      asks.delete(id)
      return
    }
    post({ event: 'answered', sessionID })
  }
  return {
    ...withHeaders,
    'chat.message': async (input, output) => {
      await pin(input, output)
    },
    event: async ({ event }) => {
      try {
        const type = event && event.type
        const p = (event && event.properties) || {}
        switch (type) {
          case 'session.created':
          case 'session.updated':
            if (p.info && p.info.id) {
              child.set(p.info.id, Boolean(p.info.parentID))
              if (p.info.parentID && typeof p.info.agent === 'string') childAgent.set(p.info.id, p.info.agent)
            }
            return
          case 'session.deleted':
            childStopped(p.info && p.info.id)
            return
          case 'session.status': {
            const id = p.sessionID
            if (!id) return
            const status = (p.status && p.status.type) || ''
            if (await isChild(id)) {
              if (status === 'busy' && !childBusy.has(id)) {
                childBusy.add(id)
                post({ event: 'subagent-start', sessionID: id, agent: childAgent.get(id) || '' })
              } else if (status === 'idle') childStopped(id)
              return
            }
            if (status === 'busy' && !busy.has(id)) {
              busy.add(id)
              post({ event: 'working', sessionID: id })
            } else if (status === 'idle' && busy.has(id)) {
              busy.delete(id)
              post({ event: 'finished', sessionID: id })
            } else if (status === 'retry') {
              post({
                event: 'retry',
                sessionID: id,
                message: String(p.status.message || ''),
                next: p.status.next,
                reason: p.status.action && p.status.action.reason
              })
            }
            return
          }
          case 'permission.asked':
          case 'permission.v2.asked':
            ask(p.id, p.sessionID, clip((await subPrefix(p.sessionID)) + describePermission(p), 300))
            return
          case 'permission.replied':
          case 'permission.v2.replied':
            answered(p.requestID || p.id, p.sessionID)
            return
          case 'question.asked':
          case 'question.v2.asked':
            ask(p.id, p.sessionID, clip((await subPrefix(p.sessionID)) + describeQuestion(p), 300))
            return
          case 'question.replied':
          case 'question.rejected':
          case 'question.v2.replied':
          case 'question.v2.rejected':
            answered(p.requestID || p.id, p.sessionID)
            return
        }
      } catch {}
    }
  }
}
`
}
